<?php
/**
 * @file video_filter_field.module
 */

/**
 * Implements hook_field_formatter_info().
 */
function video_filter_field_formatter_info() { 
  return array(
    'video_filter_field_default' => array(
      'label' => t('Video Filter'),
      'field types' => array('text'),
    ),
  );
} 

/**
 * Implements hook_field_formatter_view().
 */
function video_filter_field_formatter_view($obj_type, $object, $field, 
                                           $instance, $langcode, $items, 
                                           $display) { 

/*
dsm($obj_type, 'obj_type');
dsm($object, 'object');
dsm($field, 'field');
dsm($instance,'instance');
dsm($langcode,'langcode');
dsm($display,'display');
dsm($items,'items');
// */

  $elements = array();
  foreach ($items as $delta => $item) {
    $url = $item['safe_value'];
    $text = "[video:$url]";

    $elements[$delta] = array(
      '#theme' => 'video_filter_field_default_formatter',
      '#item' => video_filter_field_process($text),
    );
  }

  return $elements;
}

/**
 * Implements hook_theme().
 */
function video_filter_field_theme() {
  return array(
    'video_filter_field_default_formatter' => array(
      'variables' => array('item' => NULL),
    ),
  );
  
}

/**
 * Returns HTML for a video_filter_field_formatter
 */
function theme_video_filter_field_default_formatter($variables) {
  $output = $variables['item'];

  return $output;
}

/**
 * Implement video_filter processing from video_filter module.
 * 
 * @see _video_filter_process()
 */
function video_filter_field_process($text) {
$filter = new stdClass(); 
//$filter->format = ''; 
//$filter->module = 'video_filter';
//$filter->name = 'video_filter'; 
//$filter->weight = -1;
$filter->status = 1;
$filter->settings = array(
  'video_filter_width' => 400,
  'video_filter_height' => 400,
  'video_filter_autoplay' => 1,
  'video_filter_related' => 1,
);

    $text = (string)$text; // Make sure $text is a string. 
    if (preg_match_all('/\[video(\:(.+))?( .+)?\]/isU', $text, $matches_code)) {
    foreach ($matches_code[0] as $ci => $code) {
      $video = array(
        'source' => $matches_code[2][$ci],
        'autoplay' => $filter->settings['video_filter_autoplay'],
        'related' => $filter->settings['video_filter_related'],
      );

      // Pick random out of multiple sources separated by ','
      if (strstr($video['source'], ',')) {
        $sources          = explode(',', $video['source']);
        $random           = array_rand($sources, 1);
        $video['source']  = $sources[$random];
      }

      // Load all codecs
      $codecs = module_invoke_all('codec_info');

      // Find codec
      foreach ($codecs AS $codec_name => $codec) {
        if (!is_array($codec['regexp'])) {
          $codec['regexp'] = array($codec['regexp']);
        }

        // Try different regular expressions
        foreach ($codec['regexp'] as $delta => $regexp) {
          if (preg_match($regexp, $video['source'], $matches)) {
            $video['codec'] = $codec;
            $video['codec']['delta'] = $delta;
            $video['codec']['matches'] = $matches;
            $video['codec']['codec_name'] = $codec_name; // used in theme function
            $video['codec']['control_bar_height'] = 0; // default
            break 2;
          }
        }
      }

      // Codec found
      if (isset($video['codec'])) {
        // Override default attributes
        if ($matches_code[3][$ci] && preg_match_all('/\s+([a-zA-Z_]+)\:(\s+)?([0-9a-zA-Z\/]+)/i', $matches_code[3][$ci], $matches_attributes)) {
          foreach ($matches_attributes[0] AS $ai => $attribute) {
            $video[$matches_attributes[1][$ai]] = $matches_attributes[3][$ai];
          }
        }

        // Use configured ratio if present, use that from the codec otherwise
        $ratio = 1;
        if (isset($video['ratio']) && preg_match('/(\d+)\/(\d+)/', $video['ratio'], $tratio) ) {
          //validate given ratio parameter
          $ratio = $tratio[1] / $tratio[2];
        }
        else {
          $ratio = $video['codec']['ratio'];
        }

        // Sets video width & height after any user input has been parsed.
        // First, check if user has set a width.
        if (isset($video['width']) && !isset($video['height'])) {
          $video['height'] = variable_get('video_filter_height_'.$format, 400);
        }
        // Else, if user has set height.
        elseif (isset($video['height']) && !isset($video['width'])) {
          $video['width'] = $video['height'] * $ratio;
        }
        // Maybe both?
        elseif (isset($video['height']) && isset($video['width'])) {
          $video['width'] = $video['width'];
          $video['height'] = $video['height'];
        }
        // Fall back to defaults.
        elseif (!isset($video['height']) && !isset($video['width'])) {
          $video['width'] = $filter->settings['video_filter_width'];
          $video['height'] = $filter->settings['video_filter_height'];
        }

        // Default value for control bar height
        $control_bar_height = 0;
        if (isset($video['control_bar_height'])) {
          // respect control_bar_height option if present
          $control_bar_height = $video['control_bar_height'];
        }
        elseif (isset($video['codec']['control_bar_height'])) {
          // respect setting provided by codec otherwise
          $control_bar_height = $video['codec']['control_bar_height'];
        }

        // Resize to fit within width and height repecting aspect ratio
        if ($ratio) {
          $scale_factor = min(array(($video['height']-$control_bar_height), $video['width']/($ratio)));
          $video['height'] = round($scale_factor + $control_bar_height);
          $video['width'] = round($scale_factor * $ratio);
        }

        $video['autoplay'] = (bool) $video['autoplay'];
        $video['align'] = (isset($video['align']) && in_array($video['align'], array('left', 'right', 'center'))) ? $video['align'] : NULL;

        if (is_callable($video['codec']['callback'], FALSE)) {
          $replacement = call_user_func($video['codec']['callback'], $video);
        }
        else {
          // Invalid callback
          $replacement = '<!-- VIDEO FILTER - INVALID CALLBACK IN: ' . $pattern . ' -->';
        }
      // Invalid format
      }
      else {
        $replacement = '<!-- VIDEO FILTER - INVALID CODEC IN: ' . $code . ' -->';
      }

      $text = str_replace($code, $replacement, $text);
    }
  }

  return $text;
}
