<?php
/**
 * @file video_filter_field.module
 */

/**
 * Implements hook_field_formatter_info().
 */
function video_filter_field_formatter_info() { 
  return array(
    'video_filter_field_default' => array(
      'label' => t('Video Filter'),
      'field types' => array('text'),
    ),
  );
} 

/**
 * Implements hook_field_formatter_view().
 */
function video_filter_field_formatter_view($obj_type, $object, $field, 
                                           $instance, $langcode, $items, 
                                           $display) { 

/*
dsm($obj_type, 'obj_type');
dsm($object, 'object');
dsm($field, 'field');
dsm($instance,'instance');
dsm($langcode,'langcode');
dsm($display,'display');
dsm($items,'items');
// */

// TESTING
//$text = '[video:http://www.youtube.com/watch?v=Jr8n0ww3pio]';
//$text = video_filter_field_process($text);
//$item = $text; // TESTING 

  $elements = array();
  foreach ($items as $delta => $item) {
    $url = $item['safe_value'];
    $text = "[video:$url]";

    $elements[$delta] = array(
      '#theme' => 'video_filter_field_default_formatter',
      '#item' => video_filter_field_process($text),
    );
  }

  return $elements;
}

/**
 * Implements hook_theme().
 */
function video_filter_field_theme() {
  return array(
    'video_filter_field_default_formatter' => array(
      'variables' => array('item' => NULL),
    ),
  );
  
}

/**
 * Returns HTML for a video_filter_field_formatter
 */
function theme_video_filter_field_default_formatter($variables) {
  $output = $variables['item'];

  return $output;
}
